language: php

services:
  - docker

before_install:
- docker pull prabhakaran2304/docker-php-apache-ubuntu
- docker run -d -p 127.0.0.1:80 prabhakaran2304/docker-php-apache-ubuntu  
- docker ps -a

script:
- bundle exec rake test
