sudo: required

services:
  - docker

before_install:
- docker pull prabhakaran2304/docker-php-apache-ubuntu:1.0.0
- docker run -d --rm -p 80:80 --name phphello prabhakaran2304/docker-php-apache-ubuntu:1.0.0

script:
- docker images
- docker ps -a
- curl -I http://0.0.0.0/site1/index.html
